# -*- coding: utf-8 -*-
"""YDownloader.ipynb

Automatically generated by Colaboratory.


# **Dependencies**
------
"""

!pip install pytube
!pip install pandas

from pytube import YouTube
import pandas as pd

"""## **Initialize Commands**

---


"""

def download(a:str):
    url = YouTube(a)
    video = url.streams.first()
    video.download()

def Possible_quality(link:str):
  url = YouTube(link)
  video=url.streams.filter(progressive=True)
  return video

def get_highest(link:str):
    url = YouTube(link)
    video = url.streams.get_highest_resolution()
    video.download()

def get_lowest(link:str):
    url = YouTube(link)
    video = url.streams.get_lowest_resolution() 
    video.download()

def Generator(d:list):
  res=[]
  fps=[]
  typ=[]
  size=[]
  mim=[]
  main=dict()
  for i in d:
    res.append(i.resolution)
    try:
      fps.append(int(i.fps))
    except:
      fps.append(0)
    typ.append(i.type)
    size.append(int(i.filesize_mb*10)/10)
    mim.append(str(i.mime_type).split("/")[1])
  main={
      "Resolution": res,
      "FPS":fps,
      "Size (Mb) ":size,
      "Type":typ,
      "Mim Type":mim
  }
  return main

d=[]
def main_data(link:str):
  d=Possible_quality(link)
  k=Generator(d)
  frame=pd.DataFrame(k)
  frame.index=frame.index+1
  frame["FPS"]=frame.FPS.apply(lambda x: int(x))
  the_d=d
  return(frame,d)

def save(i,d,filename="Video"):
  d[i-1].download(filename=filename)

"""# **Main Part**"""

link=("https://www.youtube.com/watch?v=KCioI0tosUo")

#Get highest quality

get_highest(link)

#Get lowest quality

get_lowest(link)

#Show All Data
s=main_data(link)
s[0]

#Save data                      
                
IndexNo=6                    
Filename="video1"             

save(IndexNo,s[1],Filename)
